package app.d6d.ui.content

import app.d6d.rules.character.Ability
import app.d6d.rules.character.Ability.CHARISMA
import app.d6d.rules.character.Ability.CONSTITUTION
import app.d6d.rules.character.Ability.DEXTERITY
import app.d6d.rules.character.Ability.INTELLIGENCE
import app.d6d.rules.character.Ability.STRENGTH
import app.d6d.rules.character.Ability.WISDOM
import app.d6d.rules.character.CharacterClassId
import app.d6d.sheet.ArmorClassMethod

/**
 * Le tre squadre incluse con l'app, una per grado di esperienza.
 *
 * Dodici personaggi per dodici classi dello SRD: chi apre un template trova
 * sempre un esempio compilato della classe che gli interessa. I punteggi seguono
 * la serie consigliata con i due incrementi del background gia' applicati, cosi'
 * ogni scheda e' rifacibile a mano dall'utente senza sorprese.
 */
internal object TemplateParties {

    /** Serie consigliata 15/14/13/12/10/8 con +2 e +1 del background. */
    private fun scores(
        strength: Int,
        dexterity: Int,
        constitution: Int,
        intelligence: Int,
        wisdom: Int,
        charisma: Int,
    ): Map<Ability, Int> = mapOf(
        STRENGTH to strength,
        DEXTERITY to dexterity,
        CONSTITUTION to constitution,
        INTELLIGENCE to intelligence,
        WISDOM to wisdom,
        CHARISMA to charisma,
    )

    /** Squadra del 1º livello: le quattro classi con cui si impara il gioco. */
    val novices: List<TemplateCharacterPlan> = listOf(
        TemplateCharacterPlan(
            id = "pg-tarvos",
            name = "Tarvos di Pietrafredda",
            classId = CharacterClassId.FIGHTER,
            level = 1,
            species = "Umano",
            background = "Sentinella di frontiera",
            alignment = "Legale Neutrale",
            languages = "Comune, Nanico",
            scores = scores(17, 13, 15, 10, 12, 8),
            preferences = listOf(
                "feat:origin:aggressore-selvaggio",
                "skill:atletica",
                "skill:percezione",
                "weapon:spada-lunga",
                "weapon:giavellotto",
                "fighting-style:difesa",
                "weapon:ascia-da-battaglia",
            ),
            abilityPriority = listOf(STRENGTH, CONSTITUTION),
            armorClassMethod = ArmorClassMethod.CHAIN_MAIL,
            shieldEquipped = true,
            appearance = "Spalle larghe, barba corta, una cicatrice bianca sullo zigomo sinistro.",
            backstory = "Dodici anni sulle mura del Vallo, finché la guarnigione non è stata sciolta.",
            equipment = "Cotta di maglia, scudo, zaino da avventuriero, corda di canapa, razioni per 5 giorni.",
        ),
        TemplateCharacterPlan(
            id = "pg-nerea",
            name = "Nerea del Faro",
            classId = CharacterClassId.CLERIC,
            level = 1,
            species = "Umano",
            background = "Custode di un faro",
            alignment = "Neutrale Buono",
            languages = "Comune, Celestiale",
            scores = scores(13, 10, 15, 8, 17, 12),
            preferences = listOf(
                "feat:origin:allerta",
                "skill:medicina",
                "skill:religione",
                "weapon:mazza",
                "weapon:balestra-leggera",
                "feature:chierico:ordine-protettore",
                "spell:fiamma-sacra",
                "spell:guida",
                "spell:luce",
                "spell:cura-ferite",
                "spell:benedizione",
                "spell:scudo-della-fede",
                "spell:parola-guaritrice",
            ),
            abilityPriority = listOf(WISDOM, CONSTITUTION),
            armorClassMethod = ArmorClassMethod.SCALE_MAIL,
            shieldEquipped = true,
            appearance = "Capelli raccolti, mantello incerato, un lanternino sempre acceso alla cintura.",
            backstory = "Teneva accesa la luce sugli scogli del Passo; ora la porta dove il buio è peggiore.",
            equipment = "Corazza a scaglie, scudo, simbolo sacro, olio per lanterna, bende.",
        ),
        TemplateCharacterPlan(
            id = "pg-ilvo",
            name = "Ilvo Passocorto",
            classId = CharacterClassId.ROGUE,
            level = 1,
            species = "Halfling",
            background = "Corriere di città",
            alignment = "Caotico Buono",
            languages = "Comune, Halfling",
            scores = scores(8, 17, 14, 12, 13, 10),
            preferences = listOf(
                "feat:origin:abile",
                "skill:furtivita",
                "skill:percezione",
                "skill:acrobazia",
                "skill:rapidita-di-mano",
                "weapon:spada-corta",
                "weapon:arco-corto",
                "weapon:pugnale",
            ),
            abilityPriority = listOf(DEXTERITY, CONSTITUTION),
            armorClassMethod = ArmorClassMethod.LEATHER,
            appearance = "Minuto, occhi svegli, sempre con due tasche in più del necessario.",
            backstory = "Conosceva ogni tetto del quartiere basso; ora conosce ogni cunicolo delle rovine.",
            equipment = "Armatura di cuoio, arnesi da scasso, rampino, sacchetto di biglie.",
        ),
        TemplateCharacterPlan(
            id = "pg-sibilla",
            name = "Sibilla d'Ardo",
            classId = CharacterClassId.WIZARD,
            level = 1,
            species = "Elfo",
            background = "Copista di biblioteca",
            alignment = "Neutrale",
            languages = "Comune, Elfico, Draconico",
            scores = scores(8, 14, 14, 17, 12, 10),
            preferences = listOf(
                "feat:origin:iniziato-alla-magia",
                "skill:arcano",
                "skill:storia",
                // Un incantatore con Forza 8 col bastone farebbe meno danni di un
                // pugno: le armi accurate almeno usano la sua Destrezza.
                "weapon:pugnale",
                "weapon:dardo",
                "spell:dardo-di-fuoco",
                "spell:raggio-di-gelo",
                "spell:prestidigitazione",
                "spell:dardo-incantato",
                "spell:scudo",
                "spell:sonno",
                "spell:mani-brucianti",
                "spell:armatura-magica",
                "spell:individuazione-del-magico",
            ),
            abilityPriority = listOf(INTELLIGENCE, CONSTITUTION),
            appearance = "Dita macchiate d'inchiostro, occhiali di cristallo appesi al collo.",
            backstory = "Ha copiato per anni libri che non poteva leggere. Poi ne ha letto uno.",
            equipment = "Libro degli incantesimi, borsa delle componenti, calamaio, tre candele.",
        ),
    )

    /** Squadra del 4º livello: gia' rodata, con la prima sottoclasse alle spalle. */
    val veterans: List<TemplateCharacterPlan> = listOf(
        TemplateCharacterPlan(
            id = "pg-gudrun",
            name = "Gudrun Spaccascudi",
            classId = CharacterClassId.BARBARIAN,
            level = 4,
            species = "Mezzorco",
            background = "Guida delle terre alte",
            alignment = "Caotico Neutrale",
            languages = "Comune, Orchesco",
            scores = scores(17, 14, 16, 8, 12, 10),
            preferences = listOf(
                "feat:origin:aggressore-selvaggio",
                "skill:atletica",
                "skill:sopravvivenza",
                "weapon:ascia-bipenne",
                "weapon:giavellotto",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(STRENGTH, CONSTITUTION),
            appearance = "Alta una spanna più di chiunque altro, treccia laterale, zanne corte.",
            backstory = "Portava le carovane oltre i passi. Una di quelle carovane non è mai arrivata.",
            equipment = "Ascia bipenne, giavellotti, pelli da viaggio, corno da segnale.",
        ),
        TemplateCharacterPlan(
            id = "pg-lyra",
            name = "Lyra Voceargento",
            classId = CharacterClassId.BARD,
            level = 4,
            species = "Umano",
            background = "Cantastorie da fiera",
            alignment = "Caotico Buono",
            languages = "Comune, Silvano",
            scores = scores(8, 14, 14, 10, 12, 17),
            preferences = listOf(
                "feat:origin:abile",
                "skill:persuasione",
                "skill:inganno",
                "skill:storia",
                "weapon:pugnale",
                "weapon:balestra-leggera",
                "spell:beffa-crudele",
                "spell:luci-danzanti",
                "spell:cura-ferite",
                "spell:charme-su-persone",
                "spell:sussurri-dissonanti",
                "spell:eroismo",
                "spell:invisibilita",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(CHARISMA, DEXTERITY),
            armorClassMethod = ArmorClassMethod.LEATHER,
            appearance = "Giacca rattoppata di velluto, liuto con una crepa riparata d'argento.",
            backstory = "Canta le imprese altrui da tanto tempo da volerne finalmente una propria.",
            equipment = "Liuto, armatura di cuoio, stocco, quaderno di ballate.",
        ),
        TemplateCharacterPlan(
            id = "pg-aelis",
            name = "Aelis Corvorosso",
            classId = CharacterClassId.RANGER,
            level = 4,
            species = "Mezzelfo",
            background = "Battitrice di confine",
            alignment = "Neutrale Buono",
            languages = "Comune, Elfico",
            scores = scores(12, 17, 14, 10, 15, 8),
            preferences = listOf(
                "feat:origin:allerta",
                "skill:sopravvivenza",
                "skill:percezione",
                "skill:natura",
                "weapon:arco-lungo",
                "weapon:spada-corta",
                "fighting-style:tiro",
                "spell:marchio-del-cacciatore",
                "spell:cura-ferite",
                "spell:passo-veloce",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(DEXTERITY, WISDOM),
            armorClassMethod = ArmorClassMethod.STUDDED_LEATHER,
            appearance = "Mantello grigioverde, una piuma nera legata alla faretra.",
            backstory = "Segue le tracce di ciò che ha bruciato il suo villaggio, e sa che l'ha quasi raggiunto.",
            equipment = "Arco lungo, quaranta frecce, cuoio borchiato, trappole a laccio.",
        ),
        TemplateCharacterPlan(
            id = "pg-ysolde",
            name = "Ysolde Fiammadraco",
            classId = CharacterClassId.SORCERER,
            level = 4,
            species = "Draconide",
            background = "Erede di una casata caduta",
            alignment = "Neutrale",
            languages = "Comune, Draconico",
            scores = scores(8, 14, 15, 12, 10, 17),
            preferences = listOf(
                "feat:origin:allerta",
                "skill:arcano",
                "skill:intimidire",
                "weapon:pugnale",
                "weapon:balestra-leggera",
                "spell:dardo-di-fuoco",
                "spell:prestidigitazione",
                "spell:luce",
                "spell:mani-brucianti",
                "spell:globo-cromatico",
                "spell:frantumare",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(CHARISMA, CONSTITUTION),
            appearance = "Scaglie ramate lungo gli zigomi, occhi che riflettono la luce del fuoco.",
            backstory = "L'ultima della sua casata: il sangue che l'ha rovinata è anche ciò che la rende pericolosa.",
            equipment = "Pugnale cerimoniale, anello con sigillo, mantello foderato di rosso.",
        ),
    )

    /** Squadra del 20º livello: il tetto dello SRD, per provare lo scontro finale. */
    val legends: List<TemplateCharacterPlan> = listOf(
        TemplateCharacterPlan(
            id = "pg-aldemar",
            name = "Aldemar della Fiamma Ferma",
            classId = CharacterClassId.PALADIN,
            level = 20,
            species = "Umano",
            background = "Cavaliere di un ordine disciolto",
            alignment = "Legale Buono",
            languages = "Comune, Celestiale",
            scores = scores(17, 10, 14, 8, 12, 15),
            preferences = listOf(
                "feat:origin:allerta",
                "skill:persuasione",
                "skill:religione",
                "weapon:spada-lunga",
                "weapon:giavellotto",
                "fighting-style:difesa",
                "spell:punizione-divina",
                "spell:favore-divino",
                "spell:cura-ferite",
                // Il Dono epico va nominato prima dell'Aumento: al 19º livello sono
                // offerti insieme, e l'Aumento — che vale a ogni livello pari —
                // altrimenti se lo prenderebbe sempre lui.
                "feat:epic-boon:dono-abilita-combattimento",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(STRENGTH, CHARISMA, CONSTITUTION),
            armorClassMethod = ArmorClassMethod.PLATE,
            shieldEquipped = true,
            appearance = "Armatura lucidata fino a specchiarsi, sopravveste bruciacchiata sul fianco.",
            backstory = "L'ordine non esiste più. Il giuramento sì, e non ha bisogno di un ordine per valere.",
            equipment = "Armatura a piastre, scudo con stemma raschiato, spada lunga, olio santo.",
        ),
        TemplateCharacterPlan(
            id = "pg-maelis",
            name = "Maelis del Bosco Alto",
            classId = CharacterClassId.DRUID,
            level = 20,
            species = "Elfo",
            background = "Custode di un bosco antico",
            alignment = "Neutrale",
            languages = "Comune, Elfico, Silvano",
            scores = scores(8, 14, 16, 12, 17, 10),
            preferences = listOf(
                "feat:origin:abile",
                "skill:natura",
                "skill:percezione",
                "weapon:pugnale",
                "weapon:dardo",
                "spell:artificio-druidico",
                "spell:produrre-fiamma",
                "spell:randello-incantato",
                "spell:cura-ferite",
                "spell:intralciare",
                "spell:invocare-il-fulmine",
                "feat:epic-boon:dono-richiamo-incantesimi",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(WISDOM, CONSTITUTION),
            armorClassMethod = ArmorClassMethod.HIDE,
            appearance = "Capelli grigio-verdi intrecciati con rametti vivi, piedi spesso scalzi.",
            backstory = "Ha visto crescere tre volte lo stesso bosco. Non ne vedrà bruciare un quarto.",
            equipment = "Armatura di pelle, falcetto, focus druidico di vischio, sacchetto di semi.",
        ),
        TemplateCharacterPlan(
            id = "pg-shen",
            name = "Shen dei Passi Silenziosi",
            classId = CharacterClassId.MONK,
            level = 20,
            species = "Umano",
            background = "Novizio di un monastero di montagna",
            alignment = "Legale Neutrale",
            languages = "Comune, Nanico",
            scores = scores(12, 17, 14, 8, 16, 10),
            preferences = listOf(
                "feat:origin:allerta",
                "skill:acrobazia",
                "skill:furtivita",
                "weapon:spada-corta",
                "weapon:dardo",
                "feat:epic-boon:dono-spirito-notturno",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(DEXTERITY, WISDOM),
            appearance = "Fascia annodata sull'avambraccio, cammina senza fare rumore neanche sulla ghiaia.",
            backstory = "Il monastero gli ha insegnato la pazienza. Il mondo gli ha insegnato la fretta.",
            equipment = "Veste da viaggio, spada corta, ciotola di legno, corda di seta.",
        ),
        TemplateCharacterPlan(
            id = "pg-nyx",
            name = "Nyx del Patto Cinereo",
            classId = CharacterClassId.WARLOCK,
            level = 20,
            species = "Tiefling",
            background = "Studiosa di rovine proibite",
            alignment = "Caotico Neutrale",
            languages = "Comune, Infernale",
            scores = scores(8, 14, 15, 12, 10, 17),
            preferences = listOf(
                "feat:origin:abile",
                "skill:arcano",
                "skill:indagare",
                "weapon:pugnale",
                "weapon:balestra-leggera",
                "spell:deflagrazione-occulta",
                "spell:beffa-crudele",
                "feature:warlock:deflagrazione-agonizzante",
                "spell:intimorire-infernale",
                "spell:paura",
                "feat:epic-boon:dono-fato",
                "feat:general:aumento-punteggi-caratteristica",
            ),
            abilityPriority = listOf(CHARISMA, CONSTITUTION),
            armorClassMethod = ArmorClassMethod.STUDDED_LEATHER,
            appearance = "Corna corte limate, occhi senza pupilla, cenere che non si toglie dalle maniche.",
            backstory = "Ha firmato per sapere. Sa. E adesso deve conviverci.",
            equipment = "Cuoio borchiato, tomo rilegato in pelle grigia, sigillo del patto, sale nero.",
        ),
    )
}
