package app.d6d.domain.combat;

public enum EventType {
    ENCOUNTER_CREATED,
    COMBATANT_ADDED,
    PARTY_SET,
    ENCOUNTER_READY,
    INITIATIVE_SET,
    INITIATIVE_ROLLED,
    INITIATIVE_ORDER_SET,
    ENCOUNTER_STARTED,
    ROUND_STARTED,
    ROUND_ENDED,
    TURN_STARTED,
    TURN_ENDED,
    ACTION_SPENT,
    MOVEMENT_SPENT,
    SPELL_SLOT_SPENT,
    ATTACK_ROLLED,
    ATTACK_MISSED,
    ATTACK_HIT,
    CRITICAL_HIT,
    DAMAGE_ROLLED,
    DAMAGE_APPLIED,
    ZERO_HIT_POINTS,
    HEALED,
    TEMPORARY_HIT_POINTS_GRANTED,
    CONDITION_APPLIED,
    CONDITION_REMOVED,
    CONDITION_EXPIRED,
    CONDITION_IMMUNE,
    CONCENTRATION_STARTED,
    CONCENTRATION_CHECKED,
    CONCENTRATION_ENDED,
    ENCOUNTER_PAUSED,
    ENCOUNTER_RESUMED,
    ENCOUNTER_RESOLVED,
    UNDO_PERFORMED,

    // Morte, stabilizzazione ed Exhaustion.
    DEATH_SAVE_ROLLED,
    STABILIZED,
    KNOCKED_OUT,
    DIED,
    EXHAUSTION_CHANGED,

    /** Correzione dichiarata di una scheda durante lo scontro. */
    COMBATANT_EDITED,

    // Mappa tattica.
    MAP_CONFIGURED,
    MAP_BACKGROUND_SET,
    COMBATANT_PLACED,
    COMBATANT_MOVED,
    COMBATANT_REMOVED_FROM_MAP
}
